export const PROJECTLIST_FETCH_REQUEST = 'FETCH_PROJECT_LIST_REQUEST';
export const PROJECTLIST_FETCH_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS';
export const PROJECTLIST_FETCH_FAILURE = 'FETCH_PROJECT_LIST_FAILURE';

export const PROJECTONE_FETCH_REQUEST = 'FETCH_PROJECT_ONE_REQUEST';
export const PROJECTONE_FETCH_SUCCESS = 'FETCH_PROJECT_ONE_SUCCESS';
export const PROJECTONE_FETCH_FAILURE = 'FETCH_PROJECT_ONE_FAILURE';

export const PROJECTONE_UPDATE_REQUEST = 'UPDATE_PROJECT_ONE_REQUEST';
export const PROJECTONE_UPDATE_SUCCESS = 'UPDATE_PROJECT_ONE_SUCCESS';
export const PROJECTONE_UPDATE_FAILURE = 'UPDATE_PROJECT_ONE_FAILURE';

export const PROJECTONE_DELETE_REQUEST = 'DELETE_PROJECT_ONE_REQUEST';
export const PROJECTONE_DELETE_SUCCESS = 'DELETE_PROJECT_ONE_SUCCESS';
export const PROJECTONE_DELETE_FAILURE = 'DELETE_PROJECT_ONE_FAILURE';

export const PROJECTONE_CREATE_REQUEST = 'CREATE_PROJECT_ONE_REQUEST';
export const PROJECTONE_CREATE_SUCCESS = 'CREATE_PROJECT_ONE_SUCCESS';
export const PROJECTONE_CREATE_FAILURE = 'CREATE_PROJECT_ONE_FAILURE';
