export const PROJECTLIST_FETCH_REQUEST = 'FETCH_PROJECT_LIST_REQUEST';
export const PROJECTLIST_FETCH_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS';
export const PROJECTLIST_FETCH_FAILURE = 'FETCH_PROJECT_LIST_FAILURE';